//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyApp.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool Used { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
